package com.greenstar.entity.tb;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * @author Syed Muhammad Hassan
 * 12th November, 2020
 */

@Entity
@Table(name="TBREPORT")
public class TBReport {
    @Id
    @Column(name="CHO_NAME")
    private String CHO_NAME;

    @Column(name="CHO_CODE")
    private String CHO_CODE;

    @Column(name="DISTRICT")
    private String DISTRICT;

    @Column(name="QUARTER")
    private String QUARTER;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDNEW")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDNEW;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDUPT")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDUPT;

    @Column(name="PBNPBRPBUPT")
    private double PBNPBRPBUPT;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDTAF")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDTAF;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDALF")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDALF;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDOPT")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDOPT;

    @Column(name="PBTAFPBALFPBOPT")
    private double PBTAFPBALFPBOPT;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDNEW")
    private double PULMONARYCLINICALLYDIAGNOSEDNEW;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDRELAPSE")
    private double PULMONARYCLINICALLYDIAGNOSEDRELAPSE;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDUPT")
    private double PULMONARYCLINICALLYDIAGNOSEDUPT;

    @Column(name="PCDNPCDRPCDUPT")
    private double PCDNPCDRPCDUPT;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDTAF")
    private double PULMONARYCLINICALLYDIAGNOSEDTAF;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDALF")
    private double PULMONARYCLINICALLYDIAGNOSEDALF;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDOPT")
    private double PULMONARYCLINICALLYDIAGNOSEDOPT;

    @Column(name="PCDTAFPCDALFPCDOPT")
    private double PCDTAFPCDALFPCDOPT;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDNEW")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDNEW;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDUPT")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDUPT;

    @Column(name="EPBNEPBREPBUPT")
    private double EPBNEPBREPBUPT;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDTAF")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDTAF;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDALF")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDALF;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDOPT")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDOPT;

    @Column(name="EPBTAFEPBALFEPBOPT")
    private double EPBTAFEPBALFEPBOPT;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDNEW")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDNEW;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDRELAPSE")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDRELAPSE;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDUPT")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDUPT;

    @Column(name="EPCDNEPCDREPCDUPT")
    private double EPCDNEPCDREPCDUPT;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDTAF")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDTAF;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDALF")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDALF;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDOPT")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDOPT;

    @Column(name="EPCDTAFEPCDALFEPCDOPT")
    private double EPCDTAFEPCDALFEPCDOPT;

    @Column(name="BPSUM")
    private double BPSUM;

    @Column(name="NEWTOTAL")
    private double NEWTOTAL;

    @Column(name="TOTALRELAPSE")
    private double TOTALRELAPSE;

    @Column(name="TOTALPTH")
    private double TOTALPTH;

    @Column(name="TOTALNRUK")
    private double TOTALNRUK;

    @Column(name="TOTALTREATMENTAFTERFAILURE")
    private double TOTALTREATMENTAFTERFAILURE;

    @Column(name="TOTALAFTERLOSSTOFOLLOWUP")
    private double TOTALAFTERLOSSTOFOLLOWUP;

    @Column(name="TOTALOTERPREVIOUSLYTREATED")
    private double TOTALOTERPREVIOUSLYTREATED;

    @Column(name="BLOCK1TOTALTOTAL")
    private double BLOCK1TOTALTOTAL;

    //row1 start
    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65;
    //row 1 end

    //row 2 start
    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEABOVE65")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEABOVE65;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65;
    //row 2 end

    //row 3 start
    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65;
    //row 3 end

    //row 4 start
    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65;
    //row 4 end


    @Column(name="TOTALNRUKPTDXPERTESTPOSITIVE")
    private double TOTALNRUKPTDXPERTESTPOSITIVE;

    @Column(name="TOTALNRUKHIVSCREENING")
    private double TOTALNRUKHIVSCREENING;

    @Column(name="TOTALNRUKHIVSCREENINGHIVRESULTPOSITIVE")
    private double TOTALNRUKHIVSCREENINGHIVRESULTPOSITIVE;

    @Column(name="TOTALNRUKHIVSCREENINGHIVRESULTPOSITIVEARTNOTNULL")
    private double TOTALNRUKHIVSCREENINGHIVRESULTPOSITIVEARTNOTNULL;

    @Column(name="RIFAMPICINRESISTANTTOTAL")
    private double RIFAMPICINRESISTANTTOTAL;

    @Column(name="RIFAMPICINRESULTSTOTAL")
    private double RIFAMPICINRESULTSTOTAL;

    @Column(name="RIFAMPICINRESISTANTPREVIOUSLYTREATED")
    private double RIFAMPICINRESISTANTPREVIOUSLYTREATED;

    @Column(name="RIFAMPICINRESULTSNEW")
    private double RIFAMPICINRESULTSNEW;

    @Column(name="RIFAMPICINRESISTANTNEW")
    private double RIFAMPICINRESISTANTNEW;

    @Column(name="RIFAMPICINRESULTSRELAPSE")
    private double RIFAMPICINRESULTSRELAPSE;

    @Column(name="RIFAMPICINRESISTANTRELAPSE")
    private double RIFAMPICINRESISTANTRELAPSE;

    @Column(name="RIFAMPICINRESULTSPREVIOUSLYTREATED")
    private double RIFAMPICINRESULTSPREVIOUSLYTREATED;


    public String getCHO_NAME() {
        return CHO_NAME;
    }

    public void setCHO_NAME(String CHO_NAME) {
        this.CHO_NAME = CHO_NAME;
    }

    public String getCHO_CODE() {
        return CHO_CODE;
    }

    public void setCHO_CODE(String CHO_CODE) {
        this.CHO_CODE = CHO_CODE;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDNEW() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDNEW;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDNEW(double PULMONARYBACTERIOLOGICALLYCONFIRMEDNEW) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDNEW = PULMONARYBACTERIOLOGICALLYCONFIRMEDNEW;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE(double PULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE = PULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE;
    }

    public double getPBNPBRPBUPT() {
        return PBNPBRPBUPT;
    }

    public void setPBNPBRPBUPT(double PBNPBRPBUPT) {
        this.PBNPBRPBUPT = PBNPBRPBUPT;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDTAF() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDTAF;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDTAF(double PULMONARYBACTERIOLOGICALLYCONFIRMEDTAF) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDTAF = PULMONARYBACTERIOLOGICALLYCONFIRMEDTAF;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDALF() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDALF;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDALF(double PULMONARYBACTERIOLOGICALLYCONFIRMEDALF) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDALF = PULMONARYBACTERIOLOGICALLYCONFIRMEDALF;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDOPT() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDOPT;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDOPT(double PULMONARYBACTERIOLOGICALLYCONFIRMEDOPT) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDOPT = PULMONARYBACTERIOLOGICALLYCONFIRMEDOPT;

    }

    public double getPBTAFPBALFPBOPT() {
        return PBTAFPBALFPBOPT;
    }

    public void setPBTAFPBALFPBOPT(double PBTAFPBALFPBOPT) {
        this.PBTAFPBALFPBOPT = PBTAFPBALFPBOPT;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDNEW() {
        return PULMONARYCLINICALLYDIAGNOSEDNEW;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDNEW(double PULMONARYCLINICALLYDIAGNOSEDNEW) {
        this.PULMONARYCLINICALLYDIAGNOSEDNEW = PULMONARYCLINICALLYDIAGNOSEDNEW;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDRELAPSE() {
        return PULMONARYCLINICALLYDIAGNOSEDRELAPSE;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDRELAPSE(double PULMONARYCLINICALLYDIAGNOSEDRELAPSE) {
        this.PULMONARYCLINICALLYDIAGNOSEDRELAPSE = PULMONARYCLINICALLYDIAGNOSEDRELAPSE;
    }

    public double getPCDNPCDRPCDUPT() {
        return PCDNPCDRPCDUPT;
    }

    public void setPCDNPCDRPCDUPT(double PCDNPCDRPCDUPT) {
        this.PCDNPCDRPCDUPT = PCDNPCDRPCDUPT;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDTAF() {
        return PULMONARYCLINICALLYDIAGNOSEDTAF;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDTAF(double PULMONARYCLINICALLYDIAGNOSEDTAF) {
        this.PULMONARYCLINICALLYDIAGNOSEDTAF = PULMONARYCLINICALLYDIAGNOSEDTAF;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDALF() {
        return PULMONARYCLINICALLYDIAGNOSEDALF;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDALF(double PULMONARYCLINICALLYDIAGNOSEDALF) {
        this.PULMONARYCLINICALLYDIAGNOSEDALF = PULMONARYCLINICALLYDIAGNOSEDALF;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDOPT() {
        return PULMONARYCLINICALLYDIAGNOSEDOPT;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDOPT(double PULMONARYCLINICALLYDIAGNOSEDOPT) {
        this.PULMONARYCLINICALLYDIAGNOSEDOPT = PULMONARYCLINICALLYDIAGNOSEDOPT;
    }

    public double getPCDTAFPCDALFPCDOPT() {
        return PCDTAFPCDALFPCDOPT;
    }

    public void setPCDTAFPCDALFPCDOPT(double PCDTAFPCDALFPCDOPT) {
        this.PCDTAFPCDALFPCDOPT = PCDTAFPCDALFPCDOPT;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDNEW() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDNEW;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDNEW(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDNEW) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDNEW = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDNEW;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDRELAPSE;
    }

    public double getEPBNEPBREPBUPT() {
        return EPBNEPBREPBUPT;
    }

    public void setEPBNEPBREPBUPT(double EPBNEPBREPBUPT) {
        this.EPBNEPBREPBUPT = EPBNEPBREPBUPT;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDTAF() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDTAF;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDTAF(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDTAF) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDTAF = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDTAF;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDALF() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDALF;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDALF(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDALF) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDALF = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDALF;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDOPT() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDOPT;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDOPT(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDOPT) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDOPT = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDOPT;
    }

    public double getEPBTAFEPBALFEPBOPT() {
        return EPBTAFEPBALFEPBOPT;
    }

    public void setEPBTAFEPBALFEPBOPT(double EPBTAFEPBALFEPBOPT) {
        this.EPBTAFEPBALFEPBOPT = EPBTAFEPBALFEPBOPT;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDNEW() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDNEW;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDNEW(double EXTRAPULMONARYCLINICALLYDIAGNOSEDNEW) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDNEW = EXTRAPULMONARYCLINICALLYDIAGNOSEDNEW;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDRELAPSE() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDRELAPSE;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDRELAPSE(double EXTRAPULMONARYCLINICALLYDIAGNOSEDRELAPSE) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDRELAPSE = EXTRAPULMONARYCLINICALLYDIAGNOSEDRELAPSE;
    }
    public double getEPCDNEPCDREPCDUPT() {
        return EPCDNEPCDREPCDUPT;
    }

    public void setEPCDNEPCDREPCDUPT(double EPCDNEPCDREPCDUPT) {
        this.EPCDNEPCDREPCDUPT = EPCDNEPCDREPCDUPT;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDTAF() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDTAF;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDTAF(double EXTRAPULMONARYCLINICALLYDIAGNOSEDTAF) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDTAF = EXTRAPULMONARYCLINICALLYDIAGNOSEDTAF;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDALF() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDALF;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDALF(double EXTRAPULMONARYCLINICALLYDIAGNOSEDALF) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDALF = EXTRAPULMONARYCLINICALLYDIAGNOSEDALF;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDOPT() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDOPT;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDOPT(double EXTRAPULMONARYCLINICALLYDIAGNOSEDOPT) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDOPT = EXTRAPULMONARYCLINICALLYDIAGNOSEDOPT;
    }

    public double getEPCDTAFEPCDALFEPCDOPT() {
        return EPCDTAFEPCDALFEPCDOPT;
    }

    public void setEPCDTAFEPCDALFEPCDOPT(double EPCDTAFEPCDALFEPCDOPT) {
        this.EPCDTAFEPCDALFEPCDOPT = EPCDTAFEPCDALFEPCDOPT;
    }

    public double getBPSUM() {
        return BPSUM;
    }

    public void setBPSUM(double BPSUM) {
        this.BPSUM = BPSUM;
    }

    public double getNEWTOTAL() {
        return NEWTOTAL;
    }

    public void setNEWTOTAL(double NEWTOTAL) {
        this.NEWTOTAL = NEWTOTAL;
    }

    public double getTOTALRELAPSE() {
        return TOTALRELAPSE;
    }

    public void setTOTALRELAPSE(double TOTALRELAPSE) {
        this.TOTALRELAPSE = TOTALRELAPSE;
    }

    public double getTOTALPTH() {
        return TOTALPTH;
    }

    public void setTOTALPTH(double TOTALPTH) {
        this.TOTALPTH = TOTALPTH;
    }

    public double getTOTALNRUK() {
        return TOTALNRUK;
    }

    public void setTOTALNRUK(double TOTALNRUK) {
        this.TOTALNRUK = TOTALNRUK;
    }

    public double getTOTALTREATMENTAFTERFAILURE() {
        return TOTALTREATMENTAFTERFAILURE;
    }

    public void setTOTALTREATMENTAFTERFAILURE(double TOTALTREATMENTAFTERFAILURE) {
        this.TOTALTREATMENTAFTERFAILURE = TOTALTREATMENTAFTERFAILURE;
    }

    public double getTOTALAFTERLOSSTOFOLLOWUP() {
        return TOTALAFTERLOSSTOFOLLOWUP;
    }

    public void setTOTALAFTERLOSSTOFOLLOWUP(double TOTALAFTERLOSSTOFOLLOWUP) {
        this.TOTALAFTERLOSSTOFOLLOWUP = TOTALAFTERLOSSTOFOLLOWUP;
    }

    public double getTOTALOTERPREVIOUSLYTREATED() {
        return TOTALOTERPREVIOUSLYTREATED;
    }

    public void setTOTALOTERPREVIOUSLYTREATED(double TOTALOTERPREVIOUSLYTREATED) {
        this.TOTALOTERPREVIOUSLYTREATED = TOTALOTERPREVIOUSLYTREATED;
    }

    public double getBLOCK1TOTALTOTAL() {
        return BLOCK1TOTALTOTAL;
    }

    public void setBLOCK1TOTALTOTAL(double BLOCK1TOTALTOTAL) {
        this.BLOCK1TOTALTOTAL = BLOCK1TOTALTOTAL;
    }

    public double getTOTALNRUKPTDXPERTESTPOSITIVE() {
        return TOTALNRUKPTDXPERTESTPOSITIVE;
    }

    public void setTOTALNRUKPTDXPERTESTPOSITIVE(double TOTALNRUKPTDXPERTESTPOSITIVE) {
        this.TOTALNRUKPTDXPERTESTPOSITIVE = TOTALNRUKPTDXPERTESTPOSITIVE;
    }

    public double getTOTALNRUKHIVSCREENING() {
        return TOTALNRUKHIVSCREENING;
    }

    public void setTOTALNRUKHIVSCREENING(double TOTALNRUKHIVSCREENING) {
        this.TOTALNRUKHIVSCREENING = TOTALNRUKHIVSCREENING;
    }

    public double getTOTALNRUKHIVSCREENINGHIVRESULTPOSITIVE() {
        return TOTALNRUKHIVSCREENINGHIVRESULTPOSITIVE;
    }

    public void setTOTALNRUKHIVSCREENINGHIVRESULTPOSITIVE(double TOTALNRUKHIVSCREENINGHIVRESULTPOSITIVE) {
        this.TOTALNRUKHIVSCREENINGHIVRESULTPOSITIVE = TOTALNRUKHIVSCREENINGHIVRESULTPOSITIVE;
    }

    public double getTOTALNRUKHIVSCREENINGHIVRESULTPOSITIVEARTNOTNULL() {
        return TOTALNRUKHIVSCREENINGHIVRESULTPOSITIVEARTNOTNULL;
    }

    public void setTOTALNRUKHIVSCREENINGHIVRESULTPOSITIVEARTNOTNULL(double TOTALNRUKHIVSCREENINGHIVRESULTPOSITIVEARTNOTNULL) {
        this.TOTALNRUKHIVSCREENINGHIVRESULTPOSITIVEARTNOTNULL = TOTALNRUKHIVSCREENINGHIVRESULTPOSITIVEARTNOTNULL;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDUPT() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDUPT;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDUPT(double PULMONARYBACTERIOLOGICALLYCONFIRMEDUPT) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDUPT = PULMONARYBACTERIOLOGICALLYCONFIRMEDUPT;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDUPT() {
        return PULMONARYCLINICALLYDIAGNOSEDUPT;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDUPT(double PULMONARYCLINICALLYDIAGNOSEDUPT) {
        this.PULMONARYCLINICALLYDIAGNOSEDUPT = PULMONARYCLINICALLYDIAGNOSEDUPT;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDUPT() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDUPT;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDUPT(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDUPT) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDUPT = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDUPT;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDUPT() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDUPT;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDUPT(double EXTRAPULMONARYCLINICALLYDIAGNOSEDUPT) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDUPT = EXTRAPULMONARYCLINICALLYDIAGNOSEDUPT;
    }

    public double getRIFAMPICINRESISTANTTOTAL() {
        return RIFAMPICINRESISTANTTOTAL;
    }

    public void setRIFAMPICINRESISTANTTOTAL(double RIFAMPICINRESISTANTTOTAL) {
        this.RIFAMPICINRESISTANTTOTAL = RIFAMPICINRESISTANTTOTAL;
    }

    public double getRIFAMPICINRESULTSTOTAL() {
        return RIFAMPICINRESULTSTOTAL;
    }

    public void setRIFAMPICINRESULTSTOTAL(double RIFAMPICINRESULTSTOTAL) {
        this.RIFAMPICINRESULTSTOTAL = RIFAMPICINRESULTSTOTAL;
    }

    public double getRIFAMPICINRESISTANTPREVIOUSLYTREATED() {
        return RIFAMPICINRESISTANTPREVIOUSLYTREATED;
    }

    public void setRIFAMPICINRESISTANTPREVIOUSLYTREATED(double RIFAMPICINRESISTANTPREVIOUSLYTREATED) {
        this.RIFAMPICINRESISTANTPREVIOUSLYTREATED = RIFAMPICINRESISTANTPREVIOUSLYTREATED;
    }

    public double getRIFAMPICINRESULTSNEW() {
        return RIFAMPICINRESULTSNEW;
    }

    public void setRIFAMPICINRESULTSNEW(double RIFAMPICINRESULTSNEW) {
        this.RIFAMPICINRESULTSNEW = RIFAMPICINRESULTSNEW;
    }

    public double getRIFAMPICINRESISTANTNEW() {
        return RIFAMPICINRESISTANTNEW;
    }

    public void setRIFAMPICINRESISTANTNEW(double RIFAMPICINRESISTANTNEW) {
        this.RIFAMPICINRESISTANTNEW = RIFAMPICINRESISTANTNEW;
    }

    public double getRIFAMPICINRESULTSRELAPSE() {
        return RIFAMPICINRESULTSRELAPSE;
    }

    public void setRIFAMPICINRESULTSRELAPSE(double RIFAMPICINRESULTSRELAPSE) {
        this.RIFAMPICINRESULTSRELAPSE = RIFAMPICINRESULTSRELAPSE;
    }

    public double getRIFAMPICINRESISTANTRELAPSE() {
        return RIFAMPICINRESISTANTRELAPSE;
    }

    public void setRIFAMPICINRESISTANTRELAPSE(double RIFAMPICINRESISTANTRELAPSE) {
        this.RIFAMPICINRESISTANTRELAPSE = RIFAMPICINRESISTANTRELAPSE;
    }

    public double getRIFAMPICINRESULTSPREVIOUSLYTREATED() {
        return RIFAMPICINRESULTSPREVIOUSLYTREATED;
    }

    public void setRIFAMPICINRESULTSPREVIOUSLYTREATED(double RIFAMPICINRESULTSPREVIOUSLYTREATED) {
        this.RIFAMPICINRESULTSPREVIOUSLYTREATED = RIFAMPICINRESULTSPREVIOUSLYTREATED;
    }

    public String getDISTRICT() {
        return DISTRICT;
    }

    public void setDISTRICT(String DISTRICT) {
        this.DISTRICT = DISTRICT;
    }

    public String getQUARTER() {
        return QUARTER;
    }

    public void setQUARTER(String QUARTER) {
        this.QUARTER = QUARTER;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEABOVE65;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65(double PULMONARYCLINICALLYDIAGNOSEDMALEABOVE65) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEABOVE65 = PULMONARYCLINICALLYDIAGNOSEDMALEABOVE65;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65(double PULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65 = PULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65;
    }
}
