package com.greenstar.entity.tb;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * @author Asad Mehmood
 * 23rd November, 2020
 */

@Entity
@Table(name="TBREPORTBLOCK2")
public class TBReportBlock2 {

    @Column(name="CHO_NAME")
    private String CHO_NAME;
    @Id
    @Column(name="CHO_CODE")
    private String CHO_CODE;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65;

    @Column(name="PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65")
    private double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDMALEABOVE65")
    private double PULMONARYCLINICALLYDIAGNOSEDMALEABOVE65;

    @Column(name="PULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65")
    private double PULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65;

    @Column(name="EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65")
    private double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65;

    @Column(name="EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65")
    private double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65;

    public String getCHO_NAME() {
        return CHO_NAME;
    }

    public void setCHO_NAME(String CHO_NAME) {
        this.CHO_NAME = CHO_NAME;
    }

    public String getCHO_CODE() {
        return CHO_CODE;
    }

    public void setCHO_CODE(String CHO_CODE) {
        this.CHO_CODE = CHO_CODE;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65(double PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65 = PULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65;
    }

    public double getPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65() {
        return PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65;
    }

    public void setPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65(double PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65) {
        this.PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65 = PULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64(double PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64 = PULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64(double PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64 = PULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65() {
        return PULMONARYCLINICALLYDIAGNOSEDMALEABOVE65;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65(double PULMONARYCLINICALLYDIAGNOSEDMALEABOVE65) {
        this.PULMONARYCLINICALLYDIAGNOSEDMALEABOVE65 = PULMONARYCLINICALLYDIAGNOSEDMALEABOVE65;
    }

    public double getPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65() {
        return PULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65;
    }

    public void setPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65(double PULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65) {
        this.PULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65 = PULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN0AND4;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN0AND4;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN5AND14;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN5AND14;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN15AND24;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN15AND24;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN25AND34;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN25AND34;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN35AND44;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN35AND44;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN45AND54;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN45AND54;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEBETWEEN55AND64;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEBETWEEN55AND64;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDMALEABOVE65;
    }

    public double getEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65() {
        return EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65;
    }

    public void setEXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65(double EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65) {
        this.EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65 = EXTRAPULMONARYBACTERIOLOGICALLYCONFIRMEDFEMALEABOVE65;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN0AND4;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN0AND4;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN5AND14;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN5AND14;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN15AND24;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN15AND24;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN25AND34;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN25AND34;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN35AND44;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN35AND44;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN45AND54;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN45AND54;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEBETWEEN55AND64;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEBETWEEN55AND64;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65(double EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65 = EXTRAPULMONARYCLINICALLYDIAGNOSEDMALEABOVE65;
    }

    public double getEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65() {
        return EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65;
    }

    public void setEXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65(double EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65) {
        this.EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65 = EXTRAPULMONARYCLINICALLYDIAGNOSEDFEMALEABOVE65;
    }
}
